CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

create table department(
    id integer not null generated by default as identity constraint department_pk primary key ,
    name varchar(255),
    department_code varchar(10),
    department_location varchar(100)
);

create table designation(
    id integer not null generated by default  as identity constraint designation_pk primary key,
    name varchar(100),
    department_id integer,
    constraint fk_department_id foreign key (department_id) references department(id) on delete cascade
);

create table employee(
    id integer not null generated by default as identity constraint employee_pk primary key,
    name varchar(255),
    phone_number bigint,
    email varchar(255) default null,
    address varchar(255),
    citizenship_number varchar(50),
    marital_status varchar(10),
    date_of_birth date,
    children integer,
    designation_id integer,
    department_id integer,
    constraint fk_department_id foreign key (department_id) references department(id) on delete cascade ,
    constraint fk_designation_id foreign key (designation_id) references designation(id) on delete cascade
);

create table leave(
    id integer not null generated by default as identity constraint leave_pk primary key,
    leave_type varchar(255),
    leave_from date,
    total_leave integer,
    leave_left integer,
    leave_to date,
    leave_days integer,
    employee_id integer,
    constraint fk_employee_id foreign key (employee_id) references employee(id) on delete cascade
);

create table salary(
    id integer not null generated by default as identity constraint salary_pk primary key,
    amount integer,
    designation_id integer,
    constraint fk_designation_id foreign key (designation_id) references designation(id) on delete cascade
);

create table vacancy(
    id integer not null generated by default as identity constraint vacancy_pk primary key,
    designation_id integer,
    no_of_vacancy integer,
    deadline date,
    about_us text,
    qualification_experience text,
    skills text,
    responsibility text,
    keynote text,
    constraint fk_designation_id foreign key (designation_id) references designation(id) on delete cascade

);

create table reports(
    id integer not null generated by default as identity constraint reports_pk primary key,
    project_report text
);

