create table "users"(
                       id integer not null generated by default as identity constraint pk_user primary key,
                       phone_number varchar(255),
                       password varchar(255),
                       roles varchar(255),
                       emp_id integer,
                       constraint fk_emp_id foreign key (emp_id) references employee(id)
);